### ISSUE TITLE
Create shopping lists with items from uploaded images

### ISSUE THREAD

**Issue by fyilmazz** [ENIAC-ETU/OptimaList#12]
New shopping lists with items should be automatically created after user accepts the created text in OCR screen. Purchase date and market can be retrieved from bills, if possible, otherwise user can manually enter them.

**Comment by mucahidcelik** [comment]
https://github.com/ENIAC-ETU/OptimaList/commit/5e8d98c290969cdee126ada3a2bbe4e8f7a49b73

**Comment by mucahidcelik** [comment]
Waiting for this issue: https://github.com/ENIAC-ETU/OptimaList/issues/11

**Comment by mucahidcelik** [comment]
Shop adding feature will be implemented after ShoppingList-Shop association added. So this issue is finished
