### ISSUE TITLE
Entegration of Android - Server for deep learning models

### ISSUE THREAD

**Issue by fyilmazz** [ENIAC-ETU/OptimaList#16]
Items and purchase dates should be send to the server in an appropriate format, and results should be retrieved from the server. Recommendation lists should be created based on these results.

Related to: https://github.com/ENIAC-ETU/OptimaList-Server/issues/1

**Comment by goksunonal** [comment]
https://github.com/ENIAC-ETU/OptimaList/commit/5d1eedfac110cdfb1a4e0284b655765342f1993f
Structures for Future Recommendations List and Deep Learning Added.

**Comment by goksunonal** [comment]
https://github.com/ENIAC-ETU/OptimaList/commit/08793d8112c828ebac0f36d618f1ab7cd966498a
Added Server Connection Structure For Deep Learning, Setted up Data Formats, Fixed Bug
