### ISSUE TITLE
Get User Location in Background

### ISSUE THREAD

**Issue by fyilmazz** [ENIAC-ETU/OptimaList#8]
User location should be accessible in background, and it should be updated every few seconds.

**Comment by goksunonal** [comment]
ccfe0ef ile başlandı

**Comment by goksunonal** [comment]
fb9fc06 ve baaa773 ile gerekli kütüphane ve izinler eklendi.

**Comment by goksunonal** [comment]
b8a8006 ile distance hesaplamaları ve gerekli durumlara göre bildirim alınması eklendi. #4 içinde bazı şeyler eklendi.

**Comment by goksunonal** [comment]
Yapılması gerekenler sağlandı.
